language: c

 os: linux
  dist: bionic
compiler: 
-clang
-gcc
before_install:
  - test -n $CC && unset CC
  install: make get-deps
 
script:	./configure && make && make test
 sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
